# 配置服务的端口号
server:
  # 具体端口号（唯一）
  port: 9001

spring:
  application:
    # spring应用的名称（唯一）
    name: server-goods
#  注册到nacos
  cloud:
    # 熔断器
#    sentinel:
#      transport:900
#        dashboard: 127.0.0.1:18080
#        port: 8719
    nacos:
#      注册中心
      discovery:
        server-addr: 127.0.0.1:8848  # nacos地址
#      配置中心
      config:
#        配置中心文件后缀
        file-extension: yaml
        server-addr: 127.0.0.1:8848  # config地址
#        共享配置的配置
        shared-configs:
          - data-id: common-email.yaml
            group: DEFAULT_GROUP
#    alicloud:
#      access-key: LTAI4GCWELu3gzMZoB9jpLwb
#      secret-key: tXNglO4z40NTr6Ll9LiqiZW17qdVms
#      oss:
#        endpoint: oss-cn-beijing.aliyuncs.com
  # 消息中间件
  rabbitmq:
    addresses: 192.168.171.129
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated  #开启异步消息确认
    publisher-returns: true # 开启confirm确认功能
    template:
      mandatory: true  # 路由失败，执行ReturnCallback

  # redis
  redis:
    host: 192.168.171.129
    port: 6379
  

  # spring限制文件上传(servlet 配置)
  servlet:
    multipart:
      max-file-size: 100MB    #上传文件的最大字节
      max-request-size: 100MB
      enabled: true

  # freemarker配置
  freemarker:
    cache: false #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0 #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试
    template-loader-path: classpath:/templates
    charset: UTF-8
    check-template-location: true
    suffix: .ftl
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request

#  设置数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zg6-zk3?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root


fdfs:
  so-timeout: 1500
  connect-timeout: 600
  tracker-list:
    - 192.168.171.129:22122  #tracker路径，TrackerList参数,支持多个
  thumb-image:
    height: 200
    width: 200
  host: http://192.168.171.129:8888/

mybatis-plus:
  type-aliases-package: com.wjs.pojo  #别名
  configuration:
    map-underscore-to-camel-case: true  #驼峰映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: uuid  #id生成策略  uuid随机生成id
#日志配置
logging:
  level:
    com.huawei: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

management:
  endpoints:
    web:
      exposure:
        include: '*'

jwt:
  privateKey: fdfkghrtortytiyuyu

feign:
  hystrix:
    enabled: true

