server:
  port: 10010

# 配置服务的名称
spring:
  application:
    # 网关服务的名称
    name: api-gateway

  redis:
    # redis的地址
    host: 192.168.171.129

  cloud:
    # nacos注册中心的地址
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 网关配置
    gateway:
      discovery:
        locator:
          enabled: true
      # 路由
      routes:
        - id: server-goods  #路由id 唯一的
          uri: lb://server-goods  # 请求微服务资源  lb表示负载均衡   deptservice 微服务的名称
          predicates: # 断言 路由规则
            - Path=/goods/**
#        - id: server-shop  #路由id 唯一的
#          uri: lb://server-shop  # 请求微服务资源  lb表示负载均衡   deptservice 微服务的名称
#          predicates: # 断言 路由规则
#            - Path=/server-shop/**
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8888"
              - "http://localhost:9001"
              - "http://localhost:10010"
              - "http://192.168.171.129:8888"
              - "http://192.168.171.129:9001"
              - "http://192.168.171.129:10010"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期

# token配置         
token:
  # 是否开启token验证
  is-token: true
  # 路由白名单
  is-token-uri: login,register,test,goods
  # jwt加密密钥
  privteKey: uewiuweirir
# ip白名单
ipAddress: 127.0.0.1,0.0.0.0
